### ISSUE TITLE
Issues with Gatsby 2.0.0

### ISSUE THREAD

**Issue by arjunrao87** [Cethy/gatsby-starter-bloomer#1]
Hey there! 
When I cloned and used this starter as is ( gatsby 1.9.x ) it worked perfectly. However, when I upgraded to 2.0.0-beta.19 the bulma/bloomer styling isnt taking effect. Do you know of any incompatibility of those packages with gatsby 2.0?
Thanks for this starter!

**Comment by Cethy** [comment]
Hey Arjun,
I didn't try gatsby 2.0 yet, so I cannot say what could be wrong.
But since you closed the issue, I guess you found a solution ? Can you share it ? :)

**Comment by arjunrao87** [comment]
Whoops didnt mean to close it without giving the resolution. I came across the Gatsby migration post after I opened the issue. Changing the way the layout component calls the children props was what helped me out. The details are on this page - https://next.gatsbyjs.org/docs/migrating-from-v1-to-v2/#update-layout-component. This starter definitely helped me understand Gatsby better, so thank you!
